/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
export * as adSponsorPaymasterSol from "./AdSponsorPaymaster.sol";
export { AdWalletSponsoredTransfer__factory } from "./AdWalletSponsoredTransfer__factory";
