/* Autogenerated file. Do not edit manually. */
/* tslint:disable */
/* eslint-disable */
import type * as adSponsorPaymasterSol from "./AdSponsorPaymaster.sol";
export type { adSponsorPaymasterSol };
export type { AdWalletSponsoredTransfer } from "./AdWalletSponsoredTransfer";
